/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_bancario;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge M
 */
public class ConsultEMP extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultEMP
     */
    public ConsultEMP() {
        initComponents();
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        Invisible();
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
        jTextField14.setText("");
        jTextField15.setText("");
        jTextField16.setText("");
        jTextField17.setText("");
        jTextField8.setEnabled(false);
        jButton4.setVisible(false);
    }
    
    Connection con = null;
    String Consulta = "";
    String Nuevo = "";
    ResultSet rs = null;
    ResultSet stmt=null;
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jTextField16 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Cedula:");
        jLabel1.setPreferredSize(new java.awt.Dimension(60, 14));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombres:");
        jLabel2.setPreferredSize(new java.awt.Dimension(60, 14));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Apellidos:");
        jLabel3.setPreferredSize(new java.awt.Dimension(60, 14));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Dirección:");
        jLabel4.setPreferredSize(new java.awt.Dimension(60, 14));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Teléfono:");
        jLabel5.setPreferredSize(new java.awt.Dimension(60, 14));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Correo:");
        jLabel6.setPreferredSize(new java.awt.Dimension(60, 14));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Contraseña:");

        jTextField1.setText("jTextField1");
        jTextField1.setPreferredSize(new java.awt.Dimension(130, 20));

        jTextField2.setText("jTextField2");
        jTextField2.setPreferredSize(new java.awt.Dimension(130, 20));

        jTextField3.setText("jTextField3");
        jTextField3.setPreferredSize(new java.awt.Dimension(130, 20));

        jTextField4.setText("jTextField4");
        jTextField4.setPreferredSize(new java.awt.Dimension(130, 20));

        jTextField5.setText("jTextField5");
        jTextField5.setPreferredSize(new java.awt.Dimension(130, 20));

        jTextField6.setText("jTextField6");
        jTextField6.setPreferredSize(new java.awt.Dimension(130, 20));

        jTextField7.setText("jTextField7");
        jTextField7.setPreferredSize(new java.awt.Dimension(130, 20));

        setBorder(null);
        setClosable(true);
        setMaximizable(true);
        setTitle("Buscar empleado");
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(1230, 400));
        setMinimumSize(new java.awt.Dimension(1230, 400));
        setPreferredSize(new java.awt.Dimension(1230, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("BUSCAR");
        jButton3.setToolTipText("Buscar");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 140, 40));

        jTextField16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField16.setText("jTextField16");
        jTextField16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField16KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 260, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel16.setText("del empleado");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 310, 50));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel18.setText("Ingrese la cédula ");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 310, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 380));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Cedula:");
        jLabel8.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Nombres:");
        jLabel9.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 90, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Apellidos:");
        jLabel10.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 90, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Dirección:");
        jLabel11.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 90, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Teléfono:");
        jLabel12.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 90, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Cargo:");
        jLabel13.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 80, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Contraseña:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Correo:");
        jLabel15.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 70, 40));

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField8.setText("jTextField8");
        jTextField8.setPreferredSize(new java.awt.Dimension(130, 20));
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 180, 40));

        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField9.setText("jTextField9");
        jTextField9.setPreferredSize(new java.awt.Dimension(130, 20));
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 160, 40));

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField10.setText("jTextField10");
        jTextField10.setPreferredSize(new java.awt.Dimension(130, 20));
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 160, 40));

        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField11.setText("jTextField11");
        jTextField11.setPreferredSize(new java.awt.Dimension(130, 20));
        jPanel2.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 180, 40));

        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField12.setText("jTextField12");
        jTextField12.setPreferredSize(new java.awt.Dimension(130, 20));
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField12KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 160, 40));

        jTextField13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField13.setText("jTextField13");
        jTextField13.setPreferredSize(new java.awt.Dimension(130, 20));
        jPanel2.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 160, 40));

        jTextField14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField14.setText("jTextField14");
        jTextField14.setPreferredSize(new java.awt.Dimension(130, 20));
        jPanel2.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 180, 40));

        jTextField15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField15.setText("jTextField15");
        jTextField15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField15KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 160, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/009-padlock-21.png"))); // NOI18N
        jButton1.setToolTipText("Guardar");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/010-padlock-1.png"))); // NOI18N
        jButton2.setToolTipText("Cancelar");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Estado:");
        jLabel17.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 60, 50));

        jTextField17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField17.setText("jTextField17");
        jPanel2.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 160, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Editar empleado");
        jButton4.setToolTipText("Editar");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 180, 50));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancel.png"))); // NOI18N
        jButton5.setToolTipText("Salir");
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 40, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 820, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // GUARDAR
        int Cedula = Integer.valueOf(jTextField8.getText());
        String Nombres = jTextField9.getText();
        String Apellidos = jTextField10.getText();
        String Direccion = jTextField11.getText();
        int Telefono = Integer.valueOf(jTextField12.getText());
        String Correo = jTextField13.getText();
        String Estado = jTextField14.getText();
        String Cargo = jTextField15.getText();
        String Contraseña = jTextField17.getText();
        
        Nuevo = "UPDATE empleado SET Nombres='"+Nombres+"',"+"Apellidos='"+Apellidos+"',"+"Direccion='"+Direccion+"',"+"Telefono="+Telefono+","+"Cargo='"+Cargo+"',"+"Correo='"+Correo+"',"+"Estado='"+Estado+"',"+"Contrasena='"+Contraseña+"' WHERE Cedula="+Cedula+";";
        if (jTextField13.getText().contains("@") && jTextField13.getText().contains(".")) {
            if (jTextField8.getText().equals("") || jTextField9.getText().equals("") || jTextField10.getText().equals("") || jTextField11.getText().equals("") || jTextField12.getText().equals("") || jTextField13.getText().equals("") || jTextField14.getText().equals("") || jTextField15.getText().equals("") || jTextField17.getText().equals("")) {
                JOptionPane.showMessageDialog(null,"Complete todos los espacios", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                     try{
                    bGUI p = new bGUI();
                    p.con = p.Conexion();
                    p.con.createStatement().execute(Nuevo);
                    Invisible();
                    JOptionPane.showMessageDialog(null, "Registro modificado correctamente","Sistema",1);
                    jButton4.setVisible(true);
                    jButton4.setVisible(false);
                }
                catch(SQLException err){
                    JOptionPane.showMessageDialog(null, err.getMessage(),"Sistema",0);
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Entrada no valida para correo", "Error", JOptionPane.ERROR_MESSAGE);
            jTextField3.requestFocus();
        }
        
            
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Cancelar
        Invisible();
        Nuevo = "SELECT * FROM empleado WHERE Cedula='"+jTextField8.getText()+"';";
        jButton4.setVisible(true);
        try{
            bGUI p = new bGUI();
            p.con = p.Conexion();
            rs = p.con.createStatement().executeQuery(Nuevo);
            rs.last();
            int numreg = rs.getRow();
            if (numreg > 0) {
                int Cedula = rs.getInt(1);
                String Nombres = rs.getString(2);
                String Apellidos = rs.getString(3);
                String Direccion = rs.getString(4);
                int Telefono = rs.getInt(5);
                String Cargo = rs.getString(6);
                String Correo = rs.getString(7);
                String Estado = rs.getString(8);
                String Contraseña = rs.getString(9);
                
                jTextField8.setText(String.valueOf(Cedula));
                jTextField9.setText(Nombres);
                jTextField10.setText(Apellidos);
                jTextField11.setText(Direccion);
                jTextField12.setText(String.valueOf(Telefono));
                jTextField13.setText(Correo);
                jTextField14.setText(Estado);
                jTextField15.setText(Cargo);
                jTextField17.setText(Contraseña);
                jButton4.setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(null, "Empleado No Encontrado","Sistema",1);
            }
        }
        catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage(),"Sistema",0);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // BUSCAR
       Nuevo = "SELECT * FROM empleado WHERE Cedula='"+jTextField16.getText()+"';";
        
        try{
            bGUI p = new bGUI();
            p.con = p.Conexion();
            rs = p.con.createStatement().executeQuery(Nuevo);
            rs.last();
            int numreg = rs.getRow();
            if (numreg > 0) {
                int Cedula = rs.getInt(1);
                String Nombres = rs.getString(2);
                String Apellidos = rs.getString(3);
                String Direccion = rs.getString(4);
                int Telefono = rs.getInt(5);
                String Cargo = rs.getString(6);
                String Correo = rs.getString(7);
                String Estado = rs.getString(8);
                String Contraseña = rs.getString(9);
                
                jTextField8.setText(String.valueOf(Cedula));
                jTextField9.setText(Nombres);
                jTextField10.setText(Apellidos);
                jTextField11.setText(Direccion);
                jTextField12.setText(String.valueOf(Telefono));
                jTextField13.setText(Correo);
                jTextField14.setText(Estado);
                jTextField15.setText(Cargo);
                jTextField17.setText(Contraseña);
                jButton4.setVisible(true);
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Empleado No Encontrado","Sistema",1);
            }
        }
        catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage(),"Sistema",0);
        }
        jTextField16.setText("");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // EDITAR
        Visible();
        jButton4.setVisible(false);
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyReleased
        // KeyReleased
        String digit = jTextField12.getText();
        char last;
        if (digit.isEmpty()) {
            //Xd
        }
        else{
            try {
                    last=digit.charAt(digit.length()-1);
                    Integer.parseInt(String.valueOf(last));
                    
            } catch (NumberFormatException nfe){
                    JOptionPane.showMessageDialog(null, "Entrada no valida", "Error", JOptionPane.ERROR_MESSAGE);
                    String write = digit.substring(0, digit.length()-1);
                    jTextField12.setText(write);
            }
        }
    }//GEN-LAST:event_jTextField12KeyReleased

    private void jTextField15KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField15KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15KeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField16KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField16KeyReleased
        // TODO add your handling code here:
        String digit = jTextField16.getText();
        char last;
        if (digit.isEmpty()) {
            //Xd
        }
        else{
            try {
                    last=digit.charAt(digit.length()-1);
                    Integer.parseInt(String.valueOf(last));
                    
            } catch (NumberFormatException nfe){
                    JOptionPane.showMessageDialog(null, "Entrada no valida", "Error", JOptionPane.ERROR_MESSAGE);
                    String write = digit.substring(0, digit.length()-1);
                    jTextField16.setText(write);
            }
        }
    }//GEN-LAST:event_jTextField16KeyReleased

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    public void Visible(){
        jButton4.setVisible(false);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jTextField8.setEnabled(false);
        jTextField9.setEnabled(true);
        jTextField10.setEnabled(true);
        jTextField11.setEnabled(true);
        jTextField12.setEnabled(true);
        jTextField13.setEnabled(true);
        jTextField14.setEnabled(true);
        jTextField15.setEnabled(true);
        jTextField17.setEnabled(true);
    }
    public void Invisible(){
        jButton4.setVisible(true);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jTextField8.setEnabled(false);
        jTextField9.setEnabled(false);
        jTextField10.setEnabled(false);
        jTextField11.setEnabled(false);
        jTextField12.setEnabled(false);
        jTextField13.setEnabled(false);
        jTextField14.setEnabled(false);
        jTextField15.setEnabled(false);
        jTextField17.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
