/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_bancario;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge M
 */
public class EmpUSR1 extends javax.swing.JInternalFrame {
    //CONSULTAR
    
    
    /**
     * Creates new form EmpUSR1
     */
    public EmpUSR1() {
        initComponents();
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        NOeditando();
        jButton4.setVisible(false);
    }
    
    Connection con = null;
    String Consulta = "";
    String Nuevo = "";
    ResultSet rs = null;
    ResultSet stmt=null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setMaximizable(true);
        setTitle("Consulta y modificación de usuarios");
        setPreferredSize(new java.awt.Dimension(900, 384));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 384));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Cedula:");
        jLabel1.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombres:");
        jLabel2.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 90, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Apellidos:");
        jLabel3.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 80, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Dirección:");
        jLabel4.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 100, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Teléfono:");
        jLabel5.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 90, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Correo:");
        jLabel6.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 80, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Contraseña:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 40));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setText("jTextField1");
        jTextField1.setPreferredSize(new java.awt.Dimension(130, 20));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 160, 40));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.setText("jTextField2");
        jTextField2.setPreferredSize(new java.awt.Dimension(130, 20));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 180, 40));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.setText("jTextField3");
        jTextField3.setPreferredSize(new java.awt.Dimension(130, 20));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 150, 40));

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField4.setText("jTextField4");
        jTextField4.setPreferredSize(new java.awt.Dimension(130, 20));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 160, 40));

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField5.setText("jTextField5");
        jTextField5.setPreferredSize(new java.awt.Dimension(130, 20));
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 180, 40));

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField6.setText("jTextField6");
        jTextField6.setPreferredSize(new java.awt.Dimension(130, 20));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 150, 40));

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField7.setText("jTextField7");
        jTextField7.setPreferredSize(new java.awt.Dimension(130, 20));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 160, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/009-padlock-21.png"))); // NOI18N
        jButton2.setToolTipText("Guardar");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/010-padlock-1.png"))); // NOI18N
        jButton3.setToolTipText("Cancelar");
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Modificar datos");
        jButton4.setToolTipText("Editar");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 250, 40));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancel.png"))); // NOI18N
        jButton5.setToolTipText("Salir");
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 40, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 800, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel16.setText("del usuario");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 190, 50));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel18.setText("Ingrese la cédula ");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 320, 50));

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField8.setText("jTextField8");
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 290, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Search.png"))); // NOI18N
        jButton1.setText("BUSCAR");
        jButton1.setToolTipText("Buscar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 130, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 380));

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // GUARDAR
        int Cedula = Integer.valueOf(jTextField1.getText());
        String Nombres = jTextField2.getText();
        String Apellidos = jTextField3.getText();
        String Direccion = jTextField4.getText();
        int Telefono = Integer.valueOf(jTextField5.getText());
        String Correo = jTextField6.getText();
        String Contraseña = jTextField7.getText();
        
        Nuevo = "UPDATE usuario SET Nombres='"+Nombres+"',"+"Apellidos='"+Apellidos+"',"+"Direccion='"+Direccion+"',"+"Telefono="+Telefono+","+"Correo='"+Correo+"',"+"Contrasena='"+Contraseña+"' WHERE Cedula="+Cedula+";";
        if (Correo.contains("@") && Correo.contains(".")) {
            if (jTextField1.getText().equals("") || jTextField2.getText().equals("") || jTextField3.getText().equals("") || jTextField4.getText().equals("") || jTextField5.getText().equals("") || jTextField6.getText().equals("") || jTextField7.getText().equals("")) {
                JOptionPane.showMessageDialog(null,"Complete todos los espacios", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                try{
                    bGUI p = new bGUI();
                    p.con = p.Conexion();
                    p.con.createStatement().execute(Nuevo);
                    JOptionPane.showMessageDialog(null, "Registro modificado correctamente","Sistema",1);
                    NOeditando();
                    jButton4.setVisible(false);
                }
                catch(SQLException err){
                    JOptionPane.showMessageDialog(null, err.getMessage(),"Sistema",0);
                }
            }  
        }
        else{
            JOptionPane.showMessageDialog(null, "Entrada no valida", "Error", JOptionPane.ERROR_MESSAGE);
            jTextField6.requestFocus();
        }   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // CANCELAR
        NOeditando();
        Nuevo = "SELECT * FROM usuario WHERE Cedula='"+jTextField1.getText()+"';";
        
        try{
            bGUI p = new bGUI();
            p.con = p.Conexion();
            rs = p.con.createStatement().executeQuery(Nuevo);
            rs.last();
            int numreg = rs.getRow();
            if (numreg > 0) {
                int Cedula = rs.getInt(1);
                String Nombres = rs.getString(2);
                String Apellidos = rs.getString(3);
                String Direccion = rs.getString(4);
                int Telefono = rs.getInt(5);
                String Correo = rs.getString(6);
                String Contraseña = rs.getString(7);
                
                jTextField1.setText(String.valueOf(Cedula));
                jTextField2.setText(Nombres);
                jTextField3.setText(Apellidos);
                jTextField4.setText(Direccion);
                jTextField5.setText(String.valueOf(Telefono));
                jTextField6.setText(Correo);
                jTextField7.setText(Contraseña);
                jButton4.setVisible(false);
                NOeditando();
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Usuario No Encontrado","Sistema",1);
            }
        }
        catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage(),"Sistema",0);
        }
        jTextField8.setText("");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // EDITAR
        editando();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Buscar
        Nuevo = "SELECT * FROM usuario WHERE Cedula='"+jTextField8.getText()+"';";
        
        try{
            bGUI p = new bGUI();
            p.con = p.Conexion();
            rs = p.con.createStatement().executeQuery(Nuevo);
            rs.last();
            int numreg = rs.getRow();
            if (numreg > 0) {
                int Cedula = rs.getInt(1);
                String Nombres = rs.getString(2);
                String Apellidos = rs.getString(3);
                String Direccion = rs.getString(4);
                int Telefono = rs.getInt(5);
                String Correo = rs.getString(6);
                String Contraseña = rs.getString(7);
                
                jTextField1.setText(String.valueOf(Cedula));
                jTextField2.setText(Nombres);
                jTextField3.setText(Apellidos);
                jTextField4.setText(Direccion);
                jTextField5.setText(String.valueOf(Telefono));
                jTextField6.setText(Correo);
                jTextField7.setText(Contraseña);
                jButton4.setEnabled(true);
                jButton4.setVisible(true);
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Usuario No Encontrado","Sistema",1);
            }
        }
        catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage(),"Sistema",0);
        }
        jTextField8.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        // TODO add your handling code here:
        String digit = jTextField5.getText();
        char last;
        if (digit.isEmpty()) {
            //Xd
        }
        else{
            try {
                    last=digit.charAt(digit.length()-1);
                    Integer.parseInt(String.valueOf(last));
                    
            } catch (NumberFormatException nfe){
                    JOptionPane.showMessageDialog(null, "Entrada no valida", "Error", JOptionPane.ERROR_MESSAGE);
                    String write = digit.substring(0, digit.length()-1);
                    jTextField5.setText(write);
            }
        }
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // SAlir
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        // TODO add your handling code here:
        String digit = jTextField8.getText();
        char last;
        if (digit.isEmpty()) {
            //Xd
        }
        else{
            try {
                    last=digit.charAt(digit.length()-1);
                    Integer.parseInt(String.valueOf(last));
                    
            } catch (NumberFormatException nfe){
                    JOptionPane.showMessageDialog(null, "Entrada no valida", "Error", JOptionPane.ERROR_MESSAGE);
                    String write = digit.substring(0, digit.length()-1);
                    jTextField8.setText(write);
            }
        }
    }//GEN-LAST:event_jTextField8KeyReleased

    public void editando(){
        jButton2.setVisible(true);
        jButton3.setVisible(true);
        jButton1.setVisible(false);
        jTextField1.setEnabled(false);
        jTextField2.setEnabled(true);
        jTextField3.setEnabled(true);
        jTextField4.setEnabled(true);
        jTextField5.setEnabled(true);
        jTextField6.setEnabled(true);
        jTextField7.setEnabled(true);
        jTextField8.setEnabled(false);
    }
    
    public void NOeditando(){
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jButton1.setVisible(true);
        jTextField1.setEnabled(false);
        jTextField2.setEnabled(false);
        jTextField3.setEnabled(false);
        jTextField4.setEnabled(false);
        jTextField5.setEnabled(false);
        jTextField6.setEnabled(false);
        jTextField7.setEnabled(false);
        jTextField8.setEnabled(true);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
