/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_bancario;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge M
 */
public class Transacciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form Transacciones
     */
    public Transacciones() {
        initComponents();        
        jComboBox1.addItem("Credito");
        jComboBox1.addItem("Cuenta");
        jComboBox1.removeItem("Item 1");
        jComboBox1.removeItem("Item 2");
        jComboBox1.removeItem("Item 3");
        jComboBox1.removeItem("Item 4");
        jLabel2.setVisible(false);
        jComboBox2.setVisible(false);
        jComboBox2.removeAllItems();        
        jComboBox2.addItem("Retiro");
        jComboBox2.addItem("Ingreso"); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("No. Credito:");
        jLabel1.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 130, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Monto:");
        jLabel3.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 110, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Divisa:");
        jLabel5.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 90, 40));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField1.setPreferredSize(new java.awt.Dimension(130, 20));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 230, 40));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField3.setPreferredSize(new java.awt.Dimension(130, 20));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 230, 40));

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField5.setPreferredSize(new java.awt.Dimension(130, 20));
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 230, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/009-padlock-21.png"))); // NOI18N
        jButton1.setToolTipText("Guardar");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/010-padlock-1.png"))); // NOI18N
        jButton2.setToolTipText("Cancelar");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 230, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 230, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Tipo:");
        jLabel2.setToolTipText("");
        jLabel2.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 130, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 810, 370));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel18.setText("TRANSACCIONES");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 320, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Cancelar:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //GUARDAR

        if (jTextField1.getText().equals("") || jTextField3.getText().equals("") || jTextField5.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete todos los espacios", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            if(jComboBox1.getSelectedItem().equals("Credito")){
            try {
                p.con = p.Conexion();
                String algo = "SELECT IdTransaccionCre FROM transaccioncredito ORDER BY IdTransaccionCre DESC LIMIT 1";
               
                Statement e = p.con.createStatement();
                ResultSet f = e.executeQuery(algo);
                while(f.next())
                g= Integer.parseInt(f.getString(1))+1;

                String NoCredito = jTextField1.getText();
                int IdTra = g;
                String Monto = jTextField3.getText();
                String Fecha = fechaActual();
                String Divisa = jTextField5.getText();
                
                String algo2= "SELECT Saldo FROM credito where NoCredito="+NoCredito+";";
                Statement e2 = p.con.createStatement();
                ResultSet f2 = e2.executeQuery(algo2);
                while(f2.next())
                h= Double.parseDouble(f2.getString(1));
                
                PreparedStatement b = p.con.prepareStatement("UPDATE credito SET Saldo="+(h-(Integer.parseInt(Monto)))+" WHERE NoCredito="+NoCredito+";"); //Agregar el saldo al usuario que recib
                        b.executeUpdate();
                PreparedStatement b2 = p.con.prepareStatement("UPDATE credito SET UltimoPago='"+Fecha+"' WHERE NoCredito="+NoCredito+";");
                        b2.executeUpdate();
                PreparedStatement st = p.con.prepareStatement("INSERT INTO `transaccionCredito` VALUES(?,?,?,?,?)");
                st.setInt(1, IdTra);
                st.setDouble(2, Double.parseDouble(Monto));
                st.setString(3, Fecha);
                st.setInt(4, Integer.parseInt(Divisa));
                st.setInt(5, Integer.parseInt(NoCredito));
                st.executeUpdate();

                //Exitoso
                JOptionPane.showMessageDialog(null, "Registro guardado correctamente","Sistema",1);
                jTextField1.setText("");                
                jTextField3.setText("");                
                jTextField5.setText("");

            } catch (SQLException ex) {
                Logger.getLogger(EmpUSR.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            else if(jComboBox1.getSelectedItem().equals("Cuenta")){
                try {
                p.con = p.Conexion();
                String algo = "SELECT IdTransaccionCu FROM transaccioncuenta ORDER BY IdTransaccionCu DESC LIMIT 1";
               
                Statement e = p.con.createStatement();
                ResultSet f = e.executeQuery(algo);
                while(f.next())
                g= Integer.parseInt(f.getString(1))+1;

                String NoCuenta = jTextField1.getText();
                int IdTra = g;
                String Tipo = jComboBox2.getSelectedItem().toString();
                double Monto;
                if(jComboBox2.getSelectedItem().equals("Retiro")){
                    Monto = Double.parseDouble(jTextField3.getText());
                }
                else{
                    Monto = -Double.parseDouble(jTextField3.getText());
                }           
                String Fecha = fechaActual();
                String Divisa = jTextField5.getText();
                
                String algo2= "SELECT Saldo FROM cuenta where NoCuenta="+NoCuenta+";";
                Statement e2 = p.con.createStatement();
                ResultSet f2 = e2.executeQuery(algo2);
                while(f2.next())
                h= Double.parseDouble(f2.getString(1));
                
                PreparedStatement b = p.con.prepareStatement("UPDATE cuenta SET Saldo="+(h-Monto)+" WHERE NoCuenta="+NoCuenta+";"); //Agregar el saldo al usuario que recib
                        b.executeUpdate();
                PreparedStatement st = p.con.prepareStatement("INSERT INTO `transaccionCuenta` VALUES(?,?,?,?,?,?)");
                st.setInt(1, IdTra);
                st.setString(2, Tipo);
                if(jComboBox2.getSelectedItem().equals("Retiro")){
                    st.setDouble(3, Monto);
                }
                else{
                    st.setDouble(3, -Monto);
                }
                st.setString(4, Fecha);
                st.setInt(5, Integer.parseInt(Divisa));
                st.setInt(6, Integer.parseInt(NoCuenta));
                st.executeUpdate();

                //Exitoso
                JOptionPane.showMessageDialog(null, "Registro guardado correctamente","Sistema",1);
                jTextField1.setText("");                
                jTextField3.setText("");                
                jTextField5.setText("");

            } catch (SQLException ex) {
                Logger.getLogger(EmpUSR.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        // TODO add your handling code here:
        String digit = jTextField5.getText();
        char last;
        if (digit.isEmpty()) {
            //Xd
        }
        else{
            try {
                last=digit.charAt(digit.length()-1);
                Integer.parseInt(String.valueOf(last));

            } catch (NumberFormatException nfe){
                JOptionPane.showMessageDialog(null, "Entrada no valida", "Error", JOptionPane.ERROR_MESSAGE);
                String write = digit.substring(0, digit.length()-1);
                jTextField5.setText(write);
            }
        }
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        String digit = jTextField1.getText();
        char last;
        if (digit.isEmpty()) {
            //Xd
        }
        else{
            try {
                last=digit.charAt(digit.length()-1);
                Integer.parseInt(String.valueOf(last));

            } catch (NumberFormatException nfe){
                JOptionPane.showMessageDialog(null, "Entrada no valida", "Error", JOptionPane.ERROR_MESSAGE);
                String write = digit.substring(0, digit.length()-1);
                jTextField1.setText(write);
            }
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getSelectedItem().equals("Cuenta")){
            jLabel1.setText("No. Cuenta");
            jLabel2.setVisible(true);
            jComboBox2.setVisible(true);
        }
        if(jComboBox1.getSelectedItem().equals("Credito")){
            jLabel1.setText("No. Credito");
            jLabel2.setVisible(false);
            jComboBox2.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed
    public static String fechaActual(){
    
    Date fecha=new Date();
    DateFormat hourdateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");        
    return hourdateFormat.format(fecha);    
    
    
}
     bGUI p = new bGUI();
     int g;
     double h;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
